#cloud-config
package_update: true
packages:
    - apache2
runcmd:
    - sudo a2enmod ssl
    - sudo a2ensite default-ssl
    - sudo service apache2 restart
    - echo `hostname` | sudo tee /var/www/html/index.html
output:
    final: '> /dev/ttyS0'
